env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[dc2189999d830deb51d70e44e621798c642577a67918a73b588b74b73081fc01daa91a1affed9ff17f5e0c14662556a5]
    TG_TOKEN: ENCRYPTED[ebf386693dcc15fd6a95b627970f2b07b92c565d3f5d4c5f0035fd1e39063d69077af9808e22c9580f77c6dabe8440c1]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/z3zens/OrangeFox-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/z3zens/OrangeFox-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/z3zens/OrangeFox-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/z3zens/OrangeFox-CI/main/scripts/upload.sh)"
